meta_product_name: "World Universities API"
meta_title: "World Universities API - Free list of world universities"
meta_description: "World Universities API provides a list of universities worldwide, which includes names, urls, addresses, coordinates, phone numbers, social media accounts and U-Multirank pages of the universities"
